import fs from 'fs';
import matter from 'gray-matter';
import { InferGetStaticPropsType } from 'next';
import Link from 'next/link';
import path from 'path';
import Layout from '../components/Layout';
import { postFilePaths, POSTS_PATH } from '../utils/mdxUtils';

export default function Index({
  posts,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <Layout>
      <h1>Home Page</h1>
      <p>
        Click the link below to navigate to a page generated by{' '}
        <code>next-mdx-remote</code>.
      </p>
      <ul>
        {posts.map((post) => (
          <li key={post.slug}>
            <Link as={`/posts/${post.slug}`} href={`/posts/[slug]`}>
              <a>{post.data.title}</a>
            </Link>
          </li>
        ))}
      </ul>
    </Layout>
  );
}

export function getStaticProps() {
  const posts = Object.entries(postFilePaths)
    // Map the path into the static paths object required by Next.js
    .map(([slug, locales]) => {
      const filePath = `${slug}/${locales[0]}.mdx`;
      const source = fs.readFileSync(path.join(POSTS_PATH, filePath));
      const { content, data } = matter(source);

      return {
        content,
        data,
        slug,
        locales,
      };
    });

  return { props: { posts } };
}
